### ISSUE TITLE
[Meta] Array.prototype.sample

### ISSUE THREAD

**Issue by leobalter** [jquery-foundation/standards#23]
The `Array#sample` proposal ~~will be introduced to TC39 potentially in the next meeting~~.

I might champion it, and the work there is currently made by @tkellen and @ashleygwilliams.

Every feedback there is important, thanks!

**Comment by jzaefferer** [comment]
Could you add a link?

**Comment by leobalter** [comment]
I missed the link: https://github.com/awtk/Array.prototype.sample

**Comment by tkellen** [comment]
thanks @leobalter! Once I understand how this process works I would love to follow up with more proposals 💃

**Comment by ashleygwilliams** [comment]
yes! whoa blast from the past here, but yes yes this is cool and i would love to be involved in more stuff like this!

**Comment by leobalter** [comment]
Before I move this forward, we have to fill some gaps:

1. First and most important, we need to fill the proposal with use cases, covering where this method would be useful as a native resource and any pain points it address.
2. We need to [set](https://github.com/awtk/Array.prototype.sample/issues/5) [spec steps](https://github.com/awtk/Array.prototype.sample/blob/master/spec.md) for it.
3. We need to bring this to the [esdiscuss](https://esdiscuss.org/) mailing list for a pre-discussion and collect more feedback.

After these are done, I'll be able bring this to a meeting without a high risk of rejection.

**Comment by tkellen** [comment]
Thanks for the guidance @leobalter! @ashleygwilliams you wanna schedule an hour working meeting next week sometime to try to address those things? If yeah, I'll ping you on email :D

**Comment by ashleygwilliams** [comment]
yes def, @tkellen!

**Comment by leobalter** [comment]
As in the same reasons I mentioned on #33, this won't make it to the stage process for now. I'm sorry for this bit of frustration as I share at this moment, but there's not much I can do to make this part of the specs for now.
