### ISSUE TITLE
Document representatives

### ISSUE THREAD

**Issue by leobalter** [jquery-foundation/standards#29]
We need to list the current representatives of the jQuery Foundation on standards bodies and working groups. My plan is to create another .md document on this repo.

While we have many participants involved with standards, we also have people fully representing the jQuery Foundation, using @kborchers' words: "_checking in before meetings to discuss agenda items being presented or items the foundation may want to ask be added to an agenda, being at the meetings (in person as budget allows) and participating, and reporting back after meetings on decisions being made or follow-ups that may need further input from the foundation as a whole to best represent everyone’s best interest._"

---

For now I can list the following:

# TC39

- Rick Waldron - @rwaldron
- Leo Balter - @leobalter

# Web Platform WG

- Alexander Schmitz - @arschmitz

---

Dave Methvin (@dmethvin) may also be listed as the current coordinator of the standards team.

---

The document can also explain the expected work from the representatives, the following are some ideas adapted from [this repo's wiki page](https://github.com/jquery/standards/wiki/Standards-Lead):

> The jQuery Foundation invests significant resources in its efforts to drive Web standards on behalf of developers. The Standards Representatives coordinates those efforts, communicating on a regular basis with both the community and the projects hosted within the jQuery Foundation.

> The Standards Representatives will:

> - Know what Foundation projects are doing related to standards, and what departments or projects are involved to properly disseminate information and solicit feedback.
> - Act as ambassadors to the wider web development community, and provide feedback to the Foundation regarding its impact in that community.
> - State their affiliation with the jQuery Foundation, particularly in conferences or meetings where their attendance is a result of affiliation with, or funded by, the Foundation.
> - Provide a high-level summary of the meetings they attend, and distribute those reports as widely as possible. If there is no confidential information, public distribution is preferred.
> - Distribute information about upcoming standards meetings within the jQuery Foundation to ensure that they are attended by the appropriate representatives.
> - Inform the jQuery Foundation and interested projects of upcoming votes in the standards bodies, and take feedback on the appropriate way to vote on the matter.
> - Regularly provide reasonable data for expenses reimbursement regarding any available budget to attend meetings or events associated to their respective representation work.

**Comment by scottgonzalez** [comment]
Pointer Events WG - @scottgonzalez

**Comment by kborchers** [comment]
Here is our current W3C list. It would be helpful if everyone mentioned here can comment stating that they are still active in their groups and intend to work within the statements quoted in Leo's comment above or not so we can do some housekeeping and add you as team members here. Some of you are in groups that may not directly relate to the jQuery Foundation which seems fine but that should be in addition to groups that the foundation has interest in being represented. Also, it is unlikely that any travel or other costs would be covered by the foundation for work on groups that do not in some way impact us, our projects, or their users.

Julian Aubourg - @jaubourg
Testsuite Maintainers group

Kris Borchers: @kborchers
Advisory Committee Rep

Scott González: @scottgonzalez 
Pointer Events Working Group
Touch Events Community Group

Brian Kardell: @bkardell
Browser Extension Community Group
Cascading Style Sheets (CSS) Working Group
HTML Accessibility Task Force
HTML Media Extensions Working Group
Web History Community Group
Web Platform Incubator Community Group

Yehuda Katz: @wycats 
Extensible Web Community Group
HTML Media Extensions Working Group
Web Performance Working Group

David Methvin: @dmethvin 
Web Performance Working Group

Alexander Schmitz: @arschmitz
Audio Working Group
Web Platform Working Group

Mike Sherov: @mikesherov
Cascading Style Sheets (CSS) Working Group

Rick Waldron: @rwaldron
Device and Sensors Working Group
Testsuite Maintainers group

**Comment by bkardell** [comment]
I am as active in CSS/a11y/WICG as I can afford to be at the moment and I do the above already, I think.  If anyone thinks otherwise, feel free to tell me :) 

Web History CG is just something I do, there's not any sense of representation there. 

I'm not currently able to afford any time on the Browser Extension or Media Extensions CGs, but that's not to say I won't ever.  

jQuery has never paid for my travel to participate in any f2f, though I'd certainly welcome it :)

**Comment by kborchers** [comment]
> I am as active in CSS/a11y/WICG as I can afford to be at the moment and I do the above already, I think. If anyone thinks otherwise, feel free to tell me :)

I think you have been doing a great job @bkardell. I think the only thing that may change for you is instead of relaying communication through me, conversations can happen directly in this repo. Once things start getting a bit more organized we should find ways to easily ping appropriate people here as well to chime in on work that may impact them.

> Web History CG is just something I do, there's not any sense of representation there.
> 
> I'm not currently able to afford any time on the Browser Extension or Media Extensions CGs, but that's not to say I won't ever.

That's fine considering everything else you're doing. I imagine we are slightly less concerned with representation in CGs as we are in WGs.

> jQuery has never paid for my travel to participate in any f2f, though I'd certainly welcome it :)

This is something we will be working to improve to better allocate funds for WG f2f travel, etc. during the budgeting process. I think having a cleaned up list of who is participating where and at what level will help in that process.

**Comment by kborchers** [comment]
Based on the responses and activity I have seen, these folks will be removed from W3C participation (this is not related to ECMA participation) unless justification for keeping you involved and your plans for future foundation representation in these groups is sent to this issue in the next 24 hours:

@jaubourg
@wycats 
@mikesherov
@rwaldron

**Comment by leobalter** [comment]
I know @rwaldron is busy for the month, but I would guess he's still involved with the Device and Sensors Working Group.

Btw, I've never heard of a __Testsuite Maintainers group__ and couldn't find a proper link for it. It sounds interesting.

**Comment by kborchers** [comment]
@leobalter Going back to my original post though, what interest does the foundation have in the Device and Sensors WG that we should be championing? If this renewed effort in standards is to be successful, we need to be focused on standards that the foundation and its projects have an interest in and have representatives that will be actively involved in those groups. If in addition to that our reps want to be part of other groups that are of personal interest, that is fine, but first they must be actively involved in foundation standards initiatives.

**Comment by mikesherov** [comment]
I mentioned around 10 months ago I was looking for a replacement on CSSWG. SO please do remove me :-)

**Comment by scottgonzalez** [comment]
> Going back to my original post though, what interest does the foundation have in the Device and Sensors WG that we should be championing?

I'm sure there's interest from Tessel in making sure these APIs are sane and solve real world problems. @johnnyman727 @Frijol @rwaldron

**Comment by arschmitz** [comment]
@kborchers i would like to hear from @rwaldron on this but the foundation now is home to tessel which that would be of direct interest to tessel?

**Comment by leobalter** [comment]
I just confirmed with Rick Waldron in a private channel.

Yes, he is still involved with the Device and Sensors WG and as far as he knows, he's involved as a jQuery representative.

He's probably gonna answer this thread, but I wanted to anticipate as he's super busy to answer on this particular week.

**Comment by rwaldron** [comment]
@kborchers 

>  what interest does the foundation have in the Device and Sensors WG that we should be championing? If this renewed effort in standards is to be successful, we need to be focused on standards that the foundation and its projects have an interest in and have representatives that will be actively involved in those groups. If in addition to that our reps want to be part of other groups that are of personal interest, that is fine, but first they must be actively involved in foundation standards initiatives.

Maybe none at all? I was originally going to be an "Invited Expert" to work on developing my Sensor proposal into the Generic Sensor API spec. During the initial process, Dominique Hazael-Massieux informed me of the Royalty Free participation of W3C, to which I replied that I was already already a "royalty free" participant as representative to Ecma/TC-39 for the jQuery Foundation. Dom then noted that since jQuery Foundation was a member of W3C, and I was already a representative, that I should just participate as an affiliate and representative for that WG. Yehuda approved and that was that. 

I always assumed that jQuery Foundation's involvement in standards went beyond the "viewport", as champions of JavaScript specifications that are based on practical experience and not implementor whims.

**Comment by kborchers** [comment]
> I always assumed that jQuery Foundation's involvement in standards went beyond the "viewport", as champions of JavaScript specifications that are based on practical experience and not implementor whims.

This was not an incorrect assumption and I believe is the way we want to be approaching our standards involvement. That said, what we have been doing is not working. The foundation (Board and projects) as well as the greater JS/web community are mostly in the dark on what we are doing in standards unless they have a specific interest in a specification and happen to notice we're involved in some way (which in many cases has meant in name only). What I am attempting to do is reign this in a bit in order for us to have a better standards presence that represents the foundation's values and mission and the community at large in a way that is visible and has a path for input from everyone involved.

I am in no way trying to interrupt or halt important work that anyone is doing, including your work on the Generic Sensor API spec, @rwaldron. What this does illustrate though is the need for better transparency and communication between the foundation and its standards reps as well as between the community and its reps. I have a vague memory of hearing that you were working on that spec now that you have mentioned it but if someone would have asked me about it yesterday I would have not remembered. If the AC rep for an org doesn't know what we are directly involved in at the W3C and driving in the name of the foundation, surely many others are also unaware.

After that explanation Rick, I am happy to have you keep representing the foundation in that capacity in that WG. What I want to figure out is where are we not being properly represented and where should we be focusing more time and resources? I think this repo will help us determine both of those things and I am just asking folks that are representing us to chime in here so we can start with as clean of a slate as possible. I am extremely grateful for the work that @leobalter continues to put into this new start for our standards efforts and hope that we can continue to provide more and more visibility into what we are doing in that arena to everyone involved.

**Comment by dmethvin** [comment]
Mainly I think we want to (re)start things on the right foot and be sure that if we're being represented somewhere that the Foundation and projects know what is going on. That can be done by issues here, links to group work in progress, threads jquery-devs-team, or other things.
