### ISSUE TITLE
Remove appcache from html 5.1

### ISSUE THREAD

**Issue by arschmitz** [jquery-foundation/standards#31]
It has been proposed that the appcache spec be removed from html 5.1 but to leave in html 5 quoted

>Hello,

>The WP chairs and HTML editors propose removing Application Cache from the
HTML5.1 specification.

>This is a CFC to adopt this proposal to remove App Cache from HTML5.1 and
subsequent versions of HTML. If you have comments or concerns, please send
them to public-html@w3.org no later than 26th May 2016. Positive responses
are preferred and encouraged, but silence will be taken as agreement with
the proposal.

>The rationale for:

>1. App Cache does not do what developers expect, and although it has
multiple current implementations, browsers are turning to Service Worker as
a more useful solution for offline caching and resource management.

>2. The definition of App Cache will remain (unchanged) in HTML5, and browser
vendors are unlikely to devote time and effort refining App Cache in future
versions of HTML.

>3. Removing App Cache from HTML5.1 will help developers avoid adopting a
technology that is no longer being improved or enhanced, whilst leaving the
HTML5 definition as the de facto specification for agents wishing to
maintain compatibility.

>The rationale against:

>1. Web browsers will need to support App Cache for some time to come.

>2. W3C should continue to define how App Cache implementation evolves and
fits in with new work.

>Léonie on behalf of the WP chairs and HTML editors.

**Comment by arschmitz** [comment]
FWIW i'm in favor of this service works is not really there and usable yet but this won't remove from any browser any time soon and will discourage new usage

**Comment by ljharb** [comment]
It seems to me very irresponsible to remove appcache before Service Workers are standardized *and widely implemented*.

**Comment by bkardell** [comment]
To be entirely clear though, browsers will decide individually whether to remove support, this seems a given - this is about whether it remains documented as part of the standard.  There's a decent argument to be made that some browsers seem to really want to eventually remove this functionality, so keeping it documented as part of the standard only encourages new use/makes it harder to do so.  HTML 5(.0) will remain documented forever @ w3c.  I'm not really taking a strong position one way or another at this point personally, I think there are sane arguments on both sides.

**Comment by ljharb** [comment]
By removing it, browsers *may* decide to remove support, before an alternative exists. By leaving it in, browsers *must not* remove support. The way to discourage new use is to accelerate standardization of a replacement pattern.

**Comment by arschmitz** [comment]
> By removing it, browsers may decide to remove support, before an alternative exists. By leaving it in, browsers must not remove support.

That's not true standards do not force vendors to do anything just encourage

**Comment by ljharb** [comment]
Fair. However, browsers get some pretty extreme social pressure to not remove standard things. I think you'll find that browser implementors are indeed swayed by what's in the spec or not.

**Comment by scottgonzalez** [comment]
Swayed, yes, but that's not a strong word. Browser vendors are heavily influenced by web compatibility. Web compatibility matters more than inclusion in a spec in determining whether a feature is *removed* from a browser.

**Comment by markelog** [comment]
Hm, i guess it would be way cooler if specs also followed semver :).

Also, see for reference 
Chrome - https://developers.google.com/web/updates/2016/03/chrome-50-deprecations?hl=en
Firefox - https://bugzilla.mozilla.org/show_bug.cgi?id=1237782

**Comment by leobalter** [comment]
I share some concerns with @ljharb. I would prefer this could have been done when the recommendation for Service Worker is released, at least. The point is removing something without offering a stable and reliable replacement.

Other than that, I'm happy the focus is moving to a single solution for offline. Now, with the removal apparently done, I hope we have SW done and released soon.

**Comment by arschmitz** [comment]
This passed with a consensus
