### ISSUE TITLE
Navigation and Imagemap feedback

### ISSUE THREAD

**Issue by arschmitz** [jquery-foundation/standards#35]
The html group is looking for feedback on some issues related to image maps mainly

1. Do you meet them anywhere on the web today?

2. Do you know of cases where one image map is applied to two images - e.g. one at the top and another at the bottom of a page?

3. If the answer to 2 is yes, do you care whether you go through them twice, i.e. each time you meet the image, or once, where the actual `map` is in the HTML source? This probably only applies to those who navigate with the keyboard.

See also HTML issue https://github.com/w3c/html/issues/297

**Comment by AurelioDeRosa** [comment]
Hi @arschmitz.

1. The only website I know which is still using `map` is [subito.it](http://www.subito.it/#) which is quite popular in Italy. But since I can't think of any other website, I'd say `map` is dead.
2. No
3. No

**Comment by ljharb** [comment]
Old sites use them (like when we all looked at our old Geocities sites), and it would be a shame to break old sites for such a low-cost feature to support.

**Comment by jzaefferer** [comment]
> Old sites use them (like when we all looked at our old Geocities sites), and it would be a shame to break old sites for such a low-cost feature to support.

I don't think this is about removing image maps. Check out the w3c/html ticket Alex linked to for details.

**Comment by ljharb** [comment]
Sorry, my confusion :-)

**Comment by arschmitz** [comment]
Im going to close this i sent what we had for feed back
