### ISSUE TITLE
Remove <keygen> from HTML

### ISSUE THREAD

**Issue by arschmitz** [jquery-foundation/standards#36]
There is a call for consensus on removing the `keygen` element from the html 5.1 spec do to lack of implementation and only one available algorithm being outdated and insecure

w3c html issue: https://github.com/w3c/html/issues/43
PR : https://github.com/w3c/html/pull/354
firefox removal issue: https://www.w3.org/Bugs/Public/show_bug.cgi?id=13518
whatwg issue: https://github.com/whatwg/html/issues/102
TAG thread: https://lists.w3.org/Archives/Public/www-tag/2016May/0006.html

Sorry for the late notice on this but the deadline for the call for consensus is tonight

**Comment by AurelioDeRosa** [comment]
I'm happy to remove it from the specs. I haven't seen any interest in this element or adoption by websites. As far as I can tell, nobody is going to miss it.

**Comment by arschmitz** [comment]
This passed with out objection

**Comment by AurelioDeRosa** [comment]
@arschmitz has it been removed from the specs?

**Comment by leobalter** [comment]
There was a comment from @arschmitz which seems to be deleted/removed, now. 

Reading the links, it seems it's going to be removed without objections.

**Comment by arschmitz** [comment]
Sorry about that i didn't intend to delete that there were no objections

**Comment by arschmitz** [comment]
So turns out that though there was no dissent in the W3C mailing list there was in TAG and some valid points about some things missing from web crypto that keygen provided, so this is still being discussed at different levels and has not yet been moved to deprecated instead for now it will just be marked at risk in the HTML 5.1 spec
