### ISSUE TITLE
TC39 Meeting on May 2016

### ISSUE THREAD

**Issue by leobalter** [jquery-foundation/standards#38]
There's a new report file on this repo with the highlights from the meeting that happened last month in Munich.

https://github.com/jquery-foundation/standards/blob/master/reports/TC39/2016-05.md

This report is opinionated - from my pov - and does not replace the meeting notes.

Please use this issue for comments.

Thanks @kborchers and @tkellen for reviewing it.

**Comment by kborchers** [comment]
Thanks, this is awesome! I will tweet about this tomorrow when I can do it earlier in the day US time.

**Comment by jzaefferer** [comment]
Thanks for the report, this is very useful.

Regarding ES2016, what's a good resource to see what made it into the spec?

**Comment by AurelioDeRosa** [comment]
Hi @leobalter.

I have filed a couple of proposals ([`Math.randomInt(min, max)`](https://github.com/jquery-foundation/standards/issues/40) and [`Array.prototype.shuffle()`](https://github.com/jquery-foundation/standards/issues/33)) that I'd like to discuss with the Standards team. I'd also like to have some guidance on the process I should follow to eventually propose them to the ECMA group so that maybe you can discuss them in the next meeting.

**Comment by ljharb** [comment]
@jzaefferer https://github.com/tc39/proposals/blob/master/finished-proposals.md I'll have to add a column for the year, but basically anything before January X makes it into X.

**Comment by jzaefferer** [comment]
So the only new feature in ES2016 is Array.prototype.includes? And ES2017 will have string padding and the others on that table?

**Comment by ljharb** [comment]
@jzaefferer also the exponentiation operator, but yes, exactly.

**Comment by leobalter** [comment]
The new features are Array#includes and the Exponentiation Operator.

ES2016 has also got some new fixes from PRs from the tc39/ecma262's repo, but we need to find a better way to document this.

**Comment by leobalter** [comment]
@ljharb you got me by seconds

**Comment by leobalter** [comment]
All the current [stage 3](https://github.com/tc39/proposals/blob/master/README.md) proposals has a great chance to land on ES2017.

On the stage 2 proposals I would like to see landing on ES2017: `System.global`, `Shared memory and Atomics` (that's great w/ typedArrays), and `Rest/Spread Properties`.

They have a good chance, but we can't say it will happen until it happens.

**Comment by gsklee** [comment]
@leobalter The report is super helpful and provided a different angle of insight than the meeting notes 👍 
I'm currently also [aiming to](https://esdiscuss.org/topic/a-plan-to-help-tc39-become-more-open-up-to-community-contributions-and-participations) help opening up the TC39 process to make it more transparent and accessible to the whole community, and your story is an encouragement to me 😃

**Comment by leobalter** [comment]
Thanks, @gsklee!

I'm closing this issue as we can get ready for the next meeting report.
