### ISSUE TITLE
Template literal revision link in the report 404s

### ISSUE THREAD

**Issue by igorT** [jquery-foundation/standards#42]
In https://github.com/jquery-foundation/standards/blob/master/reports/TC39/2016-05.md there is a link to http://disnetdev.com/template-literal-revision/ which is a 404

**Comment by leobalter** [comment]
Thanks for the report, the link apparently went away. I'll try to find a new one to replace.

**Comment by ljharb** [comment]
https://github.com/tc39/proposal-template-literal-revision seems to be the original one. (ping @disnet)

**Comment by arschmitz** [comment]
https://rawgit.com/tc39/proposal-template-literal-revision/master/proposal.html

**Comment by disnet** [comment]
The updated proposal url is [https://tc39.github.io/proposal-template-literal-revision/](https://tc39.github.io/proposal-template-literal-revision/).
