### ISSUE TITLE
TC39 Meeting on July 2016

### ISSUE THREAD

**Issue by leobalter** [jquery-foundation/standards#46]
The meeting is happening next week and you can check the [agenda here](https://github.com/tc39/agendas/blob/master/2016/07.md).

My plans for the meetings consist on:

- present a new proposal for [`Object.enumerable{Keys,Values,Entries}`](https://github.com/leobalter/object-enumerables), hopefully moving it from stage 0 to 1
- Support a PR to tc39/ecma262 from Claude Pache: [Disregard lastIndex for non-global non-sticky regexps](https://github.com/tc39/ecma262/pull/627)
- Informally discuss about our current pre-proposals (see #23, #33 and #40) with other TC39 Representatives

I'm also very interested on some other topics already in the agenda:

- [Shared memory and atomics](https://github.com/tc39/ecmascript_sharedmem): This extends the use of TypedArrays in a very optimized way, and much more. This is probably the most complex theme for the next meeting but it's being worked very well. I hope it makes to stage 3.
- [System.global](https://github.com/tc39/proposal-global)
- [Promise.prototype.finally](https://github.com/ljharb/proposal-promise-finally) ~~which might conflict with cancelable promises but it is simple a gets the job done.~~ See: https://github.com/jquery-foundation/standards/issues/46#issuecomment-233408381

If you have any feedback, question or suggestion from any topic, we can use this issue to discuss.

I'll publish a report after the meeting.

**Comment by AurelioDeRosa** [comment]
Hi @leobalter. Can you expand or provide a link for "Disregard lastIndex for non-global non-sticky regexps"?

**Comment by leobalter** [comment]
np, every link can be found at the agenda but I updated the main post to add them.

**Comment by jzaefferer** [comment]
If I understood your notes correctly, the last meeting was mostly spent around tail calls. Is there any mechanism to avoid the shared memory topic to eat up all the non-timeboxed time?

**Comment by leobalter** [comment]
> Is there any mechanism to avoid the shared memory topic to eat up all the non-timeboxed time?

Technically, no. At least the time boxed items will be prioritized. I expected more items to be set as timeboxed, it didn't happen.

TC39 is trying to optimize the time management during the meetings. AFAICT, the Shared Memory proposal has a pretty active discussion on it's own repo with active reviewers with lots of questions answered. I believe if we have a +1 from the reviewers at the meeting we'll have a nice chance to get it to stage 3. I'm doing a personal review this week, as I'm interested on how it will get the tests on test262.

There's a [stage 3 milestone](https://github.com/tc39/ecmascript_sharedmem/milestone/2).

**Comment by jzaefferer** [comment]
Gotcha, thanks. 

> I expected more items to be set as timeboxed, it didn't happen.

Who sets the timeboxes?

**Comment by leobalter** [comment]
Each champion when they add an item to the agenda.

**Comment by ljharb** [comment]
(fwiw, Promise#finally was explicitly designed to *not* conflict with cancelable promises, and I've worked with its champion to ensure that's the case)

**Comment by leobalter** [comment]
That's great to know, @ljharb, thanks!

**Comment by leobalter** [comment]
- [Report](https://github.com/jquery-foundation/standards/blob/master/reports/TC39/2016-07.md)
- [meeting notes](https://github.com/rwaldron/tc39-notes/tree/master/es7/2016-07)

Reviews are welcome! Thanks in advance.

**Comment by jzaefferer** [comment]
Where can I find a code example for `Class public fields`? https://jeffmo.github.io/es-class-public-fields/ is unreadable to me.

**Comment by ljharb** [comment]
The proposal repo https://github.com/jeffmo/es-class-public-fields/ doesn't have one either - but it's basically
```js
class Foo {
  foo = bar;
}
```

Instead of
```js
class Foo {
  constructor() {
    this.foo = bar;
  }
}
```

**Comment by jzaefferer** [comment]
I see, thanks. Would be nice to add that.

I'm also interested in static class properties (much more so then non-static ones). Are those tied together?

**Comment by ljharb** [comment]
Yes, those are tied together.

**Comment by AurelioDeRosa** [comment]
Isn't

```js
class Foo {
  foo = bar;
}
```

what TypeScript does?

**Comment by ljharb** [comment]
TypeScript isn't standard JavaScript, so it's not really relevant - but I believe it does have similar syntax, yes.

**Comment by AurelioDeRosa** [comment]
Well, clearly isn't relevant in regard of what the group will decide. However, it was relevant/interesting to me, otherwise I wouldn't have asked.

**Comment by rwaldron** [comment]
Jörn,

I was actually quite surprised to see that there were no simple (nor
complex, nor anything!) use case examples in the proposal repo. I went
ahead and filed this:
https://github.com/jeffmo/es-class-public-fields/issues/46

Rick
