### ISSUE TITLE
Status Update

### ISSUE THREAD

**Issue by thysultan** [jquery-foundation/standards#63]
I found this after a [twitter thread](https://twitter.com/thysultan/status/999700946291654661). Which i assume many developers don't know this exists.

With the last activity being last year, what is the assumed status of this forum? and in what way does this give the community a voice in the TC39 committee regarding recent proposals and syntax changes to ECMAScript.

**Comment by ljharb** [comment]
The JS foundation is a TC39 member and sends delegates to meetings.

**Comment by hax** [comment]
Who are the delegates?

**Comment by jorydotcom** [comment]
@hax the delegates representing the former JS Foundation were historically Maggie Pint and Richard Gibson. The Foundation has become the OpenJS Foundation and may be electing/sending different/other delegates in the future. 

Anyone interested in the standards activities of the OpenJS Foundation should follow [openjs-foundation/standards](https://github.com/openjs-foundation/standards)

**Comment by jorydotcom** [comment]
I think this question has been addressed - please lmk if you feel otherwise!
